In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from six import StringIO
import pydotplus
import seaborn as sns
from sklearn import tree
from sklearn.tree import export_graphviz

%matplotlib inline

#Kemudian kita membaca dataset ke Pandas dengan read_csv() seperti dibawah ini
df = pd.read_csv('tb/dataset.csv')

#menampilkan 10 data pertama menggunakan  
df.head(10)

,Nama,membaca_referensi,mendengar_materi_dari_lingkungan,mempraktekkan_dalam_lingkungan,memanfaatkan_teknologi,Kemampuan_Ingg
0,nur ikhsani,5,5,5,5,Mampu
1,Dellavianti Nishfi Ilmiah Huda,5,4,5,5,Mampu
2,Lunetta,4,4,5,3,tidak Mampu
3,fanny devita inggarini,5,4,4,5,Mampu
4,Burhanudin Zuhri,3,4,4,5,Mampu
5,Khawa,4,3,5,4,tidak Mampu
6,Ike,5,5,5,5,tidak Mampu
7,Zaky Muhammad Yusuf,5,5,5,5,Mampu
8,Ajim,3,3,3,4,tidak Mampu
9,Oktaviami Manullang,5,4,5,5,Mampu

In [2]:
df.columns

Index(['Nama', ' membaca_referensi  ', 'mendengar_materi_dari_lingkungan  ',
       'mempraktekkan_dalam_lingkungan  ', ' memanfaatkan_teknologi',
       'Kemampuan_Ingg'],
      dtype='object')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 6 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Nama                                58 non-null     object
 1    membaca_referensi                  58 non-null     int64
 2   mendengar_materi_dari_lingkungan    58 non-null     int64
 3   mempraktekkan_dalam_lingkungan      58 non-null     int64
 4    memanfaatkan_teknologi             58 non-null     int64
 5   Kemampuan_Ingg                      58 non-null     object
dtypes: int64(4), object(2)
memory usage: 2.8+ KB

In [4]:
df.describe()

,membaca_referensi,mendengar_materi_dari_lingkungan,mempraktekkan_dalam_lingkungan,memanfaatkan_teknologi
count,58.000000,58.000000,58.000000,58.000000
mean,4.034483,4.034483,4.206897,4.500000
std,1.025389,1.042358,1.088353,0.842927
min,1.000000,1.000000,1.000000,1.000000
25%,3.000000,3.000000,4.000000,4.000000
50%,4.000000,4.000000,5.000000,5.000000
75%,5.000000,5.000000,5.000000,5.000000
max,5.000000,5.000000,5.000000,5.000000

In [5]:
df.isna().sum()

Nama                                  0
 membaca_referensi                    0
mendengar_materi_dari_lingkungan      0
mempraktekkan_dalam_lingkungan        0
 memanfaatkan_teknologi               0
Kemampuan_Ingg                        0
dtype: int64

In [6]:
df.nunique()

Nama                                  58
 membaca_referensi                     5
mendengar_materi_dari_lingkungan       5
mempraktekkan_dalam_lingkungan         5
 memanfaatkan_teknologi                4
Kemampuan_Ingg                         2
dtype: int64

In [7]:
data = df.copy()

In [8]:
target = 'Kemampuan_Ingg'

In [9]:
encode = ['Nama']

In [10]:
data.head()

,Nama,membaca_referensi,mendengar_materi_dari_lingkungan,mempraktekkan_dalam_lingkungan,memanfaatkan_teknologi,Kemampuan_Ingg
0,nur ikhsani,5,5,5,5,Mampu
1,Dellavianti Nishfi Ilmiah Huda,5,4,5,5,Mampu
2,Lunetta,4,4,5,3,tidak Mampu
3,fanny devita inggarini,5,4,4,5,Mampu
4,Burhanudin Zuhri,3,4,4,5,Mampu

In [11]:
for col in encode:
    dummy = pd.get_dummies(data[col], prefix=col)
    data = pd.concat([data,dummy], axis=1)
    del data[col]

In [12]:
data

,membaca_referensi,mendengar_materi_dari_lingkungan,mempraktekkan_dalam_lingkungan,memanfaatkan_teknologi,Kemampuan_Ingg,Nama_Abd rajab harahap,Nama_Abigail,Nama_Ajim,Nama_Ali Ardin Nasution,Nama_Ali ardin nasution,...,Nama_Weno Akbar,Nama_Widad Zahra Ritonga,Nama_Yunia Salsabila,Nama_Yusroh Hasibuan,Nama_Zaky Muhammad Yusuf,Nama_ali rusdi,Nama_faisal abdullah,Nama_fanny devita inggarini,Nama_indriyan ririn,Nama_nur ikhsani
0,5,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,5,4,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,4,5,3,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,4,4,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,3,4,4,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,4,3,5,4,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,5,5,5,5,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,5,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,3,3,3,4,tidak Mampu,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,5,4,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2,4,4,4,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,4,5,4,4,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,5,3,3,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13,5,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,3,3,4,3,tidak Mampu,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
15,5,5,5,4,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,4,4,5,5,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,2,1,4,5,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,4,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,4,5,4,5,tidak Mampu,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,5,4,4,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,5,5,5,4,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,5,4,3,5,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,4,4,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,4,5,4,5,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,4,4,4,4,tidak Mampu,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
26,4,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,3,3,1,1,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,4,5,4,5,Mampu,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
29,3,5,5,4,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30,3,3,3,3,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,5,1,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,4,4,4,4,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,2,2,3,4,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,3,4,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,4,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,3,4,5,5,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,4,3,4,4,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,5,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,3,4,5,5,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,4,4,5,5,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,5,5,1,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,5,5,1,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,5,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,2,2,3,3,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,5,4,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,5,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,4,5,4,5,Mampu,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
48,1,3,2,5,tidak Mampu,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,5,3,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,4,3,5,5,Mampu,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
51,5,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,5,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
53,3,3,3,3,tidak Mampu,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
54,3,3,3,3,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55,4,4,4,3,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,5,5,5,5,Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,5,5,5,5,tidak Mampu,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
target = {'Mampu':0, 'tidak Mampu':1}

In [14]:
def target_encode(val):
    return target[val]

In [15]:
data['Kemampuan_Ingg'] = data['Kemampuan_Ingg'].apply(target_encode)

In [16]:
data

,membaca_referensi,mendengar_materi_dari_lingkungan,mempraktekkan_dalam_lingkungan,memanfaatkan_teknologi,Kemampuan_Ingg,Nama_Abd rajab harahap,Nama_Abigail,Nama_Ajim,Nama_Ali Ardin Nasution,Nama_Ali ardin nasution,...,Nama_Weno Akbar,Nama_Widad Zahra Ritonga,Nama_Yunia Salsabila,Nama_Yusroh Hasibuan,Nama_Zaky Muhammad Yusuf,Nama_ali rusdi,Nama_faisal abdullah,Nama_fanny devita inggarini,Nama_indriyan ririn,Nama_nur ikhsani
0,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,5,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,4,5,3,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,4,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,3,4,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,4,3,5,4,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,5,5,5,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,3,3,3,4,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,5,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2,4,4,4,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,4,5,4,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,5,3,3,5,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,3,3,4,3,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
15,5,5,5,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,4,4,5,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,2,1,4,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,4,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,4,5,4,5,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,5,4,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,5,5,5,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,5,4,3,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,4,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,4,5,4,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,4,4,4,4,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
26,4,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,3,3,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,4,5,4,5,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
29,3,5,5,4,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30,3,3,3,3,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,5,1,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,4,4,4,4,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,2,2,3,4,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,3,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,4,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,3,4,5,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,4,3,4,4,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,3,4,5,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,4,4,5,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,5,5,1,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,5,5,1,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,2,2,3,3,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,5,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,4,5,4,5,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
48,1,3,2,5,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,5,3,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,4,3,5,5,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
51,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
53,3,3,3,3,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
54,3,3,3,3,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55,4,4,4,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,5,5,5,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
X = data.drop('Kemampuan_Ingg', axis=1)
Y = data['Kemampuan_Ingg']

In [18]:
X

,membaca_referensi,mendengar_materi_dari_lingkungan,mempraktekkan_dalam_lingkungan,memanfaatkan_teknologi,Nama_Abd rajab harahap,Nama_Abigail,Nama_Ajim,Nama_Ali Ardin Nasution,Nama_Ali ardin nasution,Nama_Amirah nahdia batubara,...,Nama_Weno Akbar,Nama_Widad Zahra Ritonga,Nama_Yunia Salsabila,Nama_Yusroh Hasibuan,Nama_Zaky Muhammad Yusuf,Nama_ali rusdi,Nama_faisal abdullah,Nama_fanny devita inggarini,Nama_indriyan ririn,Nama_nur ikhsani
0,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,5,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,4,5,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,4,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,3,4,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,4,3,5,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,3,3,3,4,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,5,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2,4,4,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,4,5,4,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,5,3,3,5,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,3,3,4,3,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
15,5,5,5,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,4,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,2,1,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,4,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,4,5,4,5,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,5,4,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,5,5,5,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,5,4,3,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,4,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,4,5,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,4,4,4,4,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
26,4,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,3,3,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,4,5,4,5,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
29,3,5,5,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30,3,3,3,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,5,1,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,4,4,4,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,2,2,3,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,3,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,4,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,3,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,4,3,4,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,3,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,4,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,5,5,1,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,5,5,1,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,2,2,3,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,5,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,4,5,4,5,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
48,1,3,2,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,5,3,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,4,3,5,5,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
51,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
53,3,3,3,3,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
54,3,3,3,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55,4,4,4,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,5,5,5,5,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [19]:
Y

0     0
1     0
2     1
3     0
4     0
5     1
6     1
7     0
8     1
9     0
10    1
11    0
12    0
13    0
14    1
15    0
16    1
17    1
18    0
19    1
20    0
21    0
22    1
23    0
24    1
25    1
26    0
27    1
28    0
29    1
30    1
31    0
32    1
33    1
34    0
35    0
36    1
37    1
38    0
39    1
40    1
41    0
42    0
43    0
44    1
45    0
46    0
47    0
48    1
49    0
50    0
51    0
52    0
53    1
54    1
55    0
56    0
57    1
Name: Kemampuan_Ingg, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=3)

print('Train set :', X_train.shape, y_train.shape)
print('Test set :', X_test.shape, y_test.shape)

Train set : (40, 62) (40,)
Test set : (18, 62) (18,)

In [21]:
Y

0     0
1     0
2     1
3     0
4     0
5     1
6     1
7     0
8     1
9     0
10    1
11    0
12    0
13    0
14    1
15    0
16    1
17    1
18    0
19    1
20    0
21    0
22    1
23    0
24    1
25    1
26    0
27    1
28    0
29    1
30    1
31    0
32    1
33    1
34    0
35    0
36    1
37    1
38    0
39    1
40    1
41    0
42    0
43    0
44    1
45    0
46    0
47    0
48    1
49    0
50    0
51    0
52    0
53    1
54    1
55    0
56    0
57    1
Name: Kemampuan_Ingg, dtype: int64

In [22]:
X_train

,membaca_referensi,mendengar_materi_dari_lingkungan,mempraktekkan_dalam_lingkungan,memanfaatkan_teknologi,Nama_Abd rajab harahap,Nama_Abigail,Nama_Ajim,Nama_Ali Ardin Nasution,Nama_Ali ardin nasution,Nama_Amirah nahdia batubara,...,Nama_Weno Akbar,Nama_Widad Zahra Ritonga,Nama_Yunia Salsabila,Nama_Yusroh Hasibuan,Nama_Zaky Muhammad Yusuf,Nama_ali rusdi,Nama_faisal abdullah,Nama_fanny devita inggarini,Nama_indriyan ririn,Nama_nur ikhsani
45,5,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,5,1,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,4,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,5,5,5,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,4,5,4,5,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,4,5,4,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,2,2,3,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
56,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,4,5,4,5,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
33,2,2,3,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,4,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
54,3,3,3,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,4,3,5,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,4,3,4,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,5,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,4,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,4,5,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,5,4,3,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,1,3,2,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,2,1,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,4,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,3,3,4,3,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
39,3,4,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,3,5,5,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
20,5,4,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,4,4,4,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
50,4,3,5,5,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
41,5,5,1,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2,4,4,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,4,5,4,5,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,5,5,5,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,5,5,5,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,3,3,3,4,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,4,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
24,4,5,4,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,5,5,1,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
from sklearn.tree import DecisionTreeClassifier

model_dtree = DecisionTreeClassifier(max_depth=3, criterion="entropy")
model_dtree.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [24]:
y_pred = model_dtree.predict(X_test)

In [25]:
print(y_pred[0:5])
print(y_test[0:5])

[0 0 1 0 0]
46    0
13    0
55    0
12    0
6     1
Name: Kemampuan_Ingg, dtype: int64

In [26]:
from sklearn.metrics import accuracy_score

print('Akurasi Decision Tree :', accuracy_score(y_test, y_pred))

Akurasi Decision Tree : 0.6666666666666666

In [27]:
import pickle

pickle.dump(model_dtree, open('modelD3.pkl', 'wb'))